/**
 * L'accesso.
 *
 * La scelta di progetto che conta: **con il codice via email non esiste la
 * distinzione fra registrarsi ed entrare.** Scrivi l'indirizzo, ricevi il
 * codice, sei dentro — e se l'account non c'era, si crea da solo. Sparisce
 * così la domanda «hai già un account?», che è il punto in cui la gente si
 * ferma davvero.
 *
 * Di conseguenza **con la password si può solo entrare, mai registrarsi**: un
 * account nasce sempre da un codice o da Google, e la password si aggiunge
 * dopo dal profilo. Sembra una limitazione, ma è ciò che tiene l'accesso a una
 * schermata sola invece che a due quasi identiche.
 */

import { useState } from "react";
import { useNavigate, useSearchParams } from "react-router";
import type { Route } from "./+types/signin";
import { authClient } from "~/lib/auth-client";
import { getUser } from "~/lib/session.server";
import { useT } from "~/i18n/use-t";
import { redirect } from "react-router";

export function meta(_: Route.MetaArgs) {
  return [{ title: "Fabula" }];
}

export async function loader({ request }: Route.LoaderArgs) {
  // Chi è già dentro non ha niente da fare qui.
  const user = await getUser(request);
  if (user) throw redirect("/");

  return { googleEnabled: Boolean(process.env.GOOGLE_CLIENT_ID) };
}

type Step =
  | { name: "email" }
  | { name: "code"; email: string }
  | { name: "password" };

export default function SignIn({ loaderData }: Route.ComponentProps) {
  const t = useT();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const [step, setStep] = useState<Step>({ name: "email" });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Solo percorsi interni: un `next` arbitrario preso dall'indirizzo è un
  // open redirect e serve a portare la gente su siti altrui dopo l'accesso.
  const rawNext = searchParams.get("next");
  const next =
    rawNext && rawNext.startsWith("/") && !rawNext.startsWith("//")
      ? rawNext
      : "/";

  /** Dopo l'accesso: se il nome non è mai stato scelto, lo chiediamo. */
  async function afterSignIn() {
    const { data } = await authClient.getSession();
    const name = data?.user?.name ?? "";
    const email = data?.user?.email ?? "";
    const looksAutoGenerated = !name || name === email.split("@")[0];

    navigate(
      looksAutoGenerated
        ? `/welcome?next=${encodeURIComponent(next)}`
        : next
    );
  }

  async function sendCode(email: string) {
    setBusy(true);
    setError(null);

    const { error: failure } = await authClient.emailOtp.sendVerificationOtp({
      email,
      type: "sign-in",
    });

    setBusy(false);
    // 429 vuol dire "hai chiesto troppi codici in un minuto", non "email
    // sbagliata" — sono due problemi diversi e il messaggio deve dirlo,
    // altrimenti sembra un guasto invece di un limite temporaneo.
    if (failure) {
      return setError(t(failure.status === 429 ? "signin.tooManyRequests" : "signin.failed"));
    }
    setStep({ name: "code", email });
  }

  return (
    <main className="mx-auto w-full max-w-md px-6 py-16">
      <h1 className="font-serif text-3xl font-semibold tracking-tight">
        {t("signin.heading")}
      </h1>

      {step.name === "email" && (
        <>
          <p className="mt-2 text-sm text-muted">{t("signin.intro")}</p>

          <form
            className="mt-8 flex flex-col gap-4"
            onSubmit={(event) => {
              event.preventDefault();
              const email = new FormData(event.currentTarget).get("email");
              if (typeof email === "string" && email) void sendCode(email);
            }}
          >
            <Field
              label={t("signin.email")}
              name="email"
              type="email"
              autoComplete="email"
              required
            />
            <Submit busy={busy} label={t("signin.sendCode")} busyLabel={t("signin.sending")} />
          </form>

          <p className="mt-4 text-sm text-muted">{t("signin.newHere")}</p>

          {loaderData.googleEnabled && (
            <>
              <Divider label={t("signin.or")} />
              <button
                type="button"
                onClick={() =>
                  authClient.signIn.social({
                    provider: "google",
                    callbackURL: next,
                  })
                }
                className="w-full rounded border border-rule px-4 py-2.5 text-sm font-medium hover:border-accent hover:text-accent"
              >
                {t("signin.google")}
              </button>
            </>
          )}

          <button
            type="button"
            onClick={() => {
              setError(null);
              setStep({ name: "password" });
            }}
            className="mt-6 text-sm text-muted underline underline-offset-4 hover:text-ink"
          >
            {t("signin.havePassword")}
          </button>
        </>
      )}

      {step.name === "code" && (
        <>
          <p className="mt-2 text-sm text-muted">
            {t("signin.codeSentTo", { email: step.email })}
          </p>

          <form
            className="mt-8 flex flex-col gap-4"
            onSubmit={async (event) => {
              event.preventDefault();
              const rawOtp = new FormData(event.currentTarget).get("otp");
              // Chi lo incolla dall'app di posta a volte si porta dietro uno
              // spazio prima o dopo: con `maxLength` a 6 basta a spostare
              // fuori dalla finestra una cifra vera e a far fallire un
              // codice che, guardato, sembra giusto.
              const otp = typeof rawOtp === "string" ? rawOtp.trim() : "";
              if (!otp) return;

              setBusy(true);
              setError(null);

              const { error: failure } = await authClient.signIn.emailOtp({
                email: step.email,
                otp,
              });

              setBusy(false);
              if (failure) {
                return setError(
                  t(failure.status === 429 ? "signin.tooManyRequests" : "signin.badCode")
                );
              }
              await afterSignIn();
            }}
          >
            <Field
              label={t("signin.code")}
              name="otp"
              inputMode="numeric"
              autoComplete="one-time-code"
              maxLength={6}
              className="text-center font-mono text-2xl tracking-[0.4em]"
              autoFocusOnMount
              required
            />
            <Submit busy={busy} label={t("signin.verify")} busyLabel={t("signin.checking")} />
          </form>

          <div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-sm">
            <button
              type="button"
              onClick={() => void sendCode(step.email)}
              className="text-muted underline underline-offset-4 hover:text-ink"
            >
              {t("signin.resend")}
            </button>
            <button
              type="button"
              onClick={() => {
                setError(null);
                setStep({ name: "email" });
              }}
              className="text-muted underline underline-offset-4 hover:text-ink"
            >
              {t("signin.otherEmail")}
            </button>
          </div>
        </>
      )}

      {step.name === "password" && (
        <>
          <p className="mt-2 text-sm text-muted">{t("signin.intro")}</p>

          <form
            className="mt-8 flex flex-col gap-4"
            onSubmit={async (event) => {
              event.preventDefault();
              const form = new FormData(event.currentTarget);
              const email = String(form.get("email") ?? "");
              const password = String(form.get("password") ?? "");

              setBusy(true);
              setError(null);

              const { error: failure } = await authClient.signIn.email({
                email,
                password,
              });

              setBusy(false);
              if (failure) return setError(t("signin.badPassword"));
              await afterSignIn();
            }}
          >
            <Field
              label={t("signin.email")}
              name="email"
              type="email"
              autoComplete="email"
              required
            />
            <Field
              label={t("signin.password")}
              name="password"
              type="password"
              autoComplete="current-password"
              required
            />
            <Submit busy={busy} label={t("signin.verify")} busyLabel={t("signin.checking")} />
          </form>

          <button
            type="button"
            onClick={() => {
              setError(null);
              setStep({ name: "email" });
            }}
            className="mt-6 text-sm text-muted underline underline-offset-4 hover:text-ink"
          >
            {t("signin.useCode")}
          </button>
        </>
      )}

      {error && (
        <p role="alert" className="mt-6 rounded bg-out-bg px-3 py-2 text-sm text-out">
          {error}
        </p>
      )}
    </main>
  );
}

/* ------------------------------------------------------------- pezzi */

function Field({
  label,
  name,
  className = "",
  autoFocusOnMount = false,
  ...rest
}: {
  label: string;
  name: string;
  className?: string;
  autoFocusOnMount?: boolean;
} & React.InputHTMLAttributes<HTMLInputElement>) {
  return (
    <div className="flex flex-col gap-1.5">
      <label
        htmlFor={name}
        className="font-mono text-[0.68rem] uppercase tracking-widest text-faint"
      >
        {label}
      </label>
      <input
        id={name}
        name={name}
        // Il focus si mette con un ref e non con `autoFocus`: la regola di
        // accessibilità vieta l'attributo, ma su un campo che è l'unico scopo
        // della schermata il focus automatico è quello che serve davvero.
        ref={(node) => {
          if (autoFocusOnMount) node?.focus();
        }}
        className={`rounded border border-rule bg-card px-3 py-2.5 text-sm focus:outline-2 focus:outline-offset-2 focus:outline-accent ${className}`}
        {...rest}
      />
    </div>
  );
}

function Submit({
  busy,
  label,
  busyLabel,
}: {
  busy: boolean;
  label: string;
  busyLabel: string;
}) {
  return (
    <button
      type="submit"
      disabled={busy}
      className="rounded bg-accent px-4 py-2.5 text-sm font-medium text-white disabled:bg-sunk disabled:text-faint"
    >
      {busy ? busyLabel : label}
    </button>
  );
}

function Divider({ label }: { label: string }) {
  return (
    <div className="my-6 flex items-center gap-4">
      <span className="h-px flex-1 bg-rule" />
      <span className="font-mono text-[0.68rem] uppercase tracking-widest text-faint">
        {label}
      </span>
      <span className="h-px flex-1 bg-rule" />
    </div>
  );
}
